// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG-Rid_atpMwHhbaBOSSTylV9WBipr-8k',
    appId: '1:245879048801:web:01627c49256ec728ab3820',
    messagingSenderId: '245879048801',
    projectId: 'grocery-app-8154c',
    authDomain: 'grocery-app-8154c.firebaseapp.com',
    storageBucket: 'grocery-app-8154c.firebasestorage.app',
    measurementId: 'G-Z45PGKD3X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBjf7vgKG3vWG_jTOM2objR2wu_HhikCE',
    appId: '1:245879048801:android:81ae1bfaa6036535ab3820',
    messagingSenderId: '245879048801',
    projectId: 'grocery-app-8154c',
    storageBucket: 'grocery-app-8154c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV-y1eHYOhqmwi6MZf39uypcS5Dvaqk6g',
    appId: '1:245879048801:ios:4fe4f5c94592c874ab3820',
    messagingSenderId: '245879048801',
    projectId: 'grocery-app-8154c',
    storageBucket: 'grocery-app-8154c.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );
}
